{{- range $i, $e := until (int .Values.brokerCount) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fanout-platform.fullname" $ }}-broker-{{ $e }}
  labels:
    {{- include "fanout-platform.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "fanout-platform.selectorLabels" $ | nindent 4 }}
    app: broker-{{ $e }}
  ports:
    - name: broker-internal-in
      port: 5360
      targetPort: 5360
    - name: broker-internal-out
      port: 5361
      targetPort: 5361
---
{{- end }}
