apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fanout-platform.fullname" . }}-broker-certs
  labels:
    {{- include "fanout-platform.labels" . | nindent 4 }}
type: Opaque
data:
  client.key: {{ .Values.brokerCerts.client }}
  client.key_secret: {{ .Values.brokerCerts.client_secret }}
  server.key: {{ .Values.brokerCerts.server }}
  server.key_secret: {{ .Values.brokerCerts.server_secret }}
