apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fanout-platform.fullname" . }}-cluster
  labels:
    {{- include "fanout-platform.labels" . | nindent 4 }}
data:
{{- if .Values.debug }}
  debug: "1"
{{- else }}
  debug: "0"
{{- end }}
  logical_region: {{ .Values.logicalRegion | quote }}
  organization_name: {{ .Values.organizationName | quote }}
  region_base: {{ .Values.regionBase | quote }}
