apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fanout-platform.fullname" . }}-cluster
  labels:
    {{- include "fanout-platform.labels" . | nindent 4 }}
data:
  api_django_secret: {{ randAlphaNum 40 | b64enc }}
