apiVersion: v1
kind: Service
metadata:
  name: {{ include "fanout-platform.fullname" . }}-conn-api
  labels:
    {{- include "fanout-platform.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "fanout-platform.selectorLabels" . | nindent 4 }}
    app: conn
  ports:
    - name: conn-api
      port: 80
      targetPort: 8005
