apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fanout-platform.fullname" . }}-conn-files
  labels:
    {{- include "fanout-platform.labels" . | nindent 4 }}
data:
  realms: |
    {{- .Values.realms | nindent 4 }}
  routes: |
    {{- .Values.routes | nindent 4 }}
