apiVersion: v1
kind: Service
metadata:
  name: {{ include "fanout-platform.fullname" . }}-db
  labels:
    {{- include "fanout-platform.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "fanout-platform.selectorLabels" . | nindent 4 }}
    app: db
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
