apiVersion: v1
kind: Service
metadata:
  name: {{ include "fanout-platform.fullname" . }}-subsproc
  labels:
    {{- include "fanout-platform.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "fanout-platform.selectorLabels" . | nindent 4 }}
    app: subsproc
  ports:
    - name: subsaggregator-internal-in
      port: 5380
      targetPort: 5380
    - name: subsaggregator-internal-out
      port: 5381
      targetPort: 5381
