apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fanout-platform.fullname" . }}-subsproc-templates
  labels:
    {{- include "fanout-platform.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "conf/subsproc/*").AsConfig | indent 2 }}
